name: Test Build

on: [pull_request]

jobs:
    build:
        runs-on: [self-hosted, linux, x64, dev]

        strategy:
            matrix:
                node-version: [19.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
                  path: dev
            - run: npm install
            - run: npm run build --if-present
            - run: cd /home/drone/.github && pm2 delete ecosystem.config.js
            - run: cd /home/drone/.github && pm2 start ecosystem.config.js
              env:
                  CI: true
